services:
  prometheus:
    build: .
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - coolify

  promtail:
    build: ./promtail
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/promtail-positions.yaml:/tmp/positions.yaml
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    environment:
      - GRAFANA_CLOUD_API_KEY=${GRAFANA_CLOUD_API_KEY}
    networks:
      - coolify

networks:
  coolify:
    external: true