services:
  prometheus:
    build: .
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true